<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Mytest\\' => array($baseDir . '/mytest'),
    'Connect_DB\\' => array($baseDir . '/connect_DB'),
    'App\\' => array($baseDir . '/app'),
);
